# redacted compose.yaml-file used by an existing Stalwart Mailserver v0.15.5 container
services:
  stalwart:
    image: stalwartlabs/stalwart:latest
    environment:
      - TZ=Europe/Amsterdam
    hostname: mail.example.com
    restart: unless-stopped
    volumes:
      - /armblock/stalwart/opt:/opt/stalwart
    ports:
      - 8080:8080
      - 8133:8133
      - 25:25
      - 465:465
      - 587:587
      - 993:993
      - 4190:4190
    dns:
      - redacted_ipv4
      - redacted_ipv6
    networks:
      - network1

networks:
  network1:
    name: my-bridge-network
    external: true
