# docker-compose.yml

services:
  exchange_gateway:
    build: .
    container_name: exchange_gateway
    restart: unless-stopped
    environment:
      - TZ=${GATEWAY_TZ:-UTC}
      - RUST_LOG=${RUST_LOG:-info}
    volumes:
      - ./exchange-gateway.config.toml:/etc/exchange-gateway/config.toml:ro
    ports:
      - "[::]:8134:8134"
    networks:
      my-bridge-network:
        ipv4_address: 172.28.0.11
        ipv6_address: fd00:dead:beef::11

networks:
  my-bridge-network:
    external: true
    enable_ipv6: true
