# stalwart-additions.toml

[server.socket."0.0.0.0:8080"]
protocol = "http"

[server.socket."[::]:8080"]
protocol = "http"

[authentication.fallback-admin]
enable = true

[storage]
backend = "rocksdb"

[certificate.acme]
enable = true

[lookup.default]
domain = "example.com"

[jmap]
enable = true

[dav]
enable = true